name: rashed_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  intl: ^0.20.2
  equatable: ^2.0.7
  get_it: ^9.2.0
  dio: ^5.7.0
  flutter_secure_storage: ^10.0.0
  firebase_messaging: ^16.1.1
  toastification: ^3.0.3
  dartz: ^0.10.1
  # Clerk for OAuth (LinkedIn)
  clerk_flutter: ^0.0.14-beta
  url_launcher: ^6.2.5
  app_links: ^7.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.7
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/animations/
    - assets/lang/en.json
    - assets/lang/ar.json

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/png/rashed_app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
